---
- hosts: all
  become: true
  tasks:
  - name: install jdk8 on ubunut20 node1
    apt:
     name: openjdk-8-jre-headless
     state: present
    when: ansible_os_family == "Debian" 

  - name: install jdk8 on amazonlinux2 node2
    yum:
     name: java-1.8.0-openjdk
     state: present
    when: ansible_os_family == "RedHat"