---
- hosts: all
  become: true
  tasks:
  - name: install webserver(apache2) on ubunut20 node
    apt:
     name: apache2
     state: present

  - name: start the apache2 service
    service:
      name: apache2
      state: started